### ISSUE TITLE
Problem with custom slug in lang switching

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-langswitcher#11]
Hello!

I have a blog post with folder `2013-10-26-background-image`. Two languages `md` in it has custom slugs: `background-image` for EN and `fonovaya-kartinka` for RU (translit).

All works fine with selected language but after language switching becomes `2013-10-26-background-image` for both langs.

Steps:
1. We have EN lang in root and go to posts: `site.com/en/posts`
2. Select our post, looks right: `site.com/en/events/background-image`
3. Change lang to RU and url becomes: `site.com/ru/events/2013-10-26-background-image`
4. Change lang to EN and url becomes the same: `site.com/en/events/2013-10-26-background-image`
Present with another initial lang in the same way.

Env:
Grav v1.1.0-rc.1
LangSwitcher v1.2.1 with standard `langswitcher.html.twig`

**Comment by Sogl** [comment]
This comment helped me:
https://github.com/getgrav/grav-plugin-langswitcher/issues/2#issuecomment-140481977

I used this toggle in Admin panel:
![image](https://cloud.githubusercontent.com/assets/7556290/16026023/fb4d7cb4-3216-11e6-94f1-758554943ed4.png)

But how it's working? Do it use 301 redirect or something?

**Comment by flaviocopes** [comment]
Yes it uses 301 redirect by default. 
Or the redirect code you setup in `system.pages.redirect_default_code`.
