### ISSUE TITLE
stylesheet is not working, I had to change the code:

### ISSUE THREAD

**Issue by Stepanov-Sergey** [getgrav/grav-plugin-langswitcher#14]
```
.langswitcher li {
    display: inline-block;
    margin-left: 0.5rem;
    line-height: 1rem;
}

.langswitcher .active {
    font-weight: bold;
    text-decoration: underline;
}
```
to

```
a.external.active
{
    font-weight: bold;
    text-decoration: underline;
}
a.external {
    display: inline-block;
    margin-left: 0.7rem;
    line-height: 1rem;
}
```
because not all themes create langswitcher class

**Comment by rhukster** [comment]
The langswitcher class is actually provided by the partial in the plugin: https://github.com/getgrav/grav-plugin-langswitcher/blob/develop/templates/partials/langswitcher.html.twig

Your CSS is too generic and would affect any link with external class.
