### ISSUE TITLE
Images support

### ISSUE THREAD

**Issue by Neuronauten** [getgrav/grav-plugin-langswitcher#15]
Would it be possible to implement images support ? Without images support the langswitcher plugin feels spoon-feeding to use text only. The flags lovers and the icon user are left out. Explicitly new ideas about language suggestion are left out also.

**Comment by flaviocopes** [comment]
The plugin provides a very basic output in its own Twig file (https://github.com/getgrav/grav-plugin-langswitcher/blob/develop/templates/partials/langswitcher.html.twig). The theme can decide to override that, and provide flags or other types of output, by adding a `templates/partials/langswitcher.html.twig` file.

**Comment by Neuronauten** [comment]
Pics and flags in the langswitcher should be implemented as a core plugin feature. It is just my personal approach. I also understand that this is at the moment a no priority thing if i compare importance with other workplaces in grav and gantry.
So please take it as a lp enhancement for future implementation or close it if it should stay a themes creator part of twigging.

**Comment by flaviocopes** [comment]
Open for a PR if someone wants to add this functionality.

**Comment by pbt39ppc** [comment]
Hi, im agree with Neuronauten that Pics and flags in the langswitcher should be implemented as a core plugin feature.
But im rhinking plugin must be able to display:
1) whole word e.g. English
2) Lang code e.g. EN
3) Flag 
4) custom image (?)

Reasons why that must be in the plugin: 
1) No problems with updates.
2) No problems with updates!
3) Same :)

**Comment by rhukster** [comment]
PRs please :)

**Comment by pbt39ppc** [comment]
english is not my native languadge, please describe, what "PRs" means?

**Comment by rhukster** [comment]
PR = Pull Request

**Comment by GreenItSolutions** [comment]
Hi,
Thank for your plugin. As mention above, switching between Text or flags would be a great enhancement.
I'm not developer and i discover grav today. I found https://github.com/lipis/flag-icon-css but i'm not able to insert this project in your plugin.

**Comment by agryson** [comment]
While I have nothing against people adding options and am aware that this is not always the dev's choice, I'd like to suggest that those wanting flags (or those who may develop the functionality for the PR) [check out this article](https://unitedlanguagegroup.com/blog/inside-design-a-language-selector-is-no-place-for-flags/).

It does an excellent job of explaining why flags are not always (except in a pretty specific case) appropriate.

As an:
- Irish man
- who speaks English
- but lives in France 
- who always has to pick between UK and US flags 
... this is a topic that is close to my heart! ^_^

**Comment by rhukster** [comment]
cleaning up old tickets...
