### ISSUE TITLE
langswitcher does not respect custom slugs

### ISSUE THREAD

**Issue by Neuronauten** [getgrav/grav-plugin-langswitcher#16]
I found that the links to visible pages called from langswitcher plugin do not respect custom slugs set in grav pages. I don't know if it is a grav or langswitcher plugin issue, please sort.

**Comment by rhukster** [comment]
Try setting:

```
pages:
  redirect_default_route: true
```

In your `user/config/system.yaml` file.

**Comment by Neuronauten** [comment]
That did it. Thanks a lot.
