### ISSUE TITLE
Arabic  not displaying properly 

### ISSUE THREAD

**Issue by rimagahwa** [getgrav/grav-plugin-langswitcher#18]
my site has 2 languages English and Arabic.
When I'm using it in Arabic Both languages are shown correctly.
But when I'm using it in English , the Arabic language title is being shown as weird symbols. (English is correct)
![about rima rimaworks](https://cloud.githubusercontent.com/assets/13506835/22945061/ea07d50e-f303-11e6-8ca0-4c6993665e1a.png)
I tested with different directions for the html lan direction , but it is the same. ( right to left ,left to right and auto).

**Comment by rhukster** [comment]
It's probably related to the font you are using not providing the required extended characters.  if you turn off webfonts, and use regular system font, how does it look?

**Comment by rimagahwa** [comment]
still the same , removed all the styles. the web default is Times.

**Comment by flaviocopes** [comment]
This is Antimatter:

![screen shot 2017-02-15 at 10 03 04](https://cloud.githubusercontent.com/assets/11783388/22967232/fb3d948c-f365-11e6-9e4f-c2359d06f285.png)

Make sure the server sends the page UTF-8 encoded. You can see that in the browser devtools:

![screen shot 2017-02-15 at 10 03 51](https://cloud.githubusercontent.com/assets/11783388/22967269/20ff75fa-f366-11e6-830e-44992d8a45a3.png)

**Comment by rimagahwa** [comment]
yeah I just checked the server was not sending it as  UTF-8. In fact it was not sending  any encoding even though there's a meta tag in the html.
I believe this is a problem that doesn't have to do with your plug in. I'll investigate the problem.
Thank you for the help.
