### ISSUE TITLE
Multi-language template partials (like menu and header

### ISSUE THREAD

**Issue by payrequestio** [getgrav/grav-plugin-langswitcher#23]
.TWIG templates have the menu,footer,header but how you can make them English & Dutch ?
So 2 versions anyone know how this is possible ?

**Comment by flaviocopes** [comment]
You can have Twig templates specific to each language (https://learn.getgrav.org/content/multi-language#language-based-twig-templates) but it's easier to use language strings for any content, and use translations https://learn.getgrav.org/content/multi-language#translation-via-twig
