### ISSUE TITLE
Editable plugin fail to work after installation of Langswitcher

### ISSUE THREAD

**Issue by mpetricek** [getgrav/grav-plugin-langswitcher#24]
Hi,

I'm building multilingual website for my client using Editable and Langswitcher plugin.

It was actually working fine when on localhost but since I moved website on my webhost editable fail to work together with Langswitcher. When I remove Langswitcher plugin everything is fine.
I see that contenttools editor is loaded when I log in in frontend but shortcodes are not processed from some reason.

Website is on subdomain at the moment [here](http://fourway.petriczech.com)

Do you have any idea what could cause the problem? 

Thank you very much!

**Comment by rhukster** [comment]
cleaning up old tickets...
