### ISSUE TITLE
Change shown name of language in language switcher

### ISSUE THREAD

**Issue by kingemir** [getgrav/grav-plugin-langswitcher#25]
for `zh` (chinese)

> 中文 (简体)

 is shown. That means simplified chinese. Where does the plugin get this information from? How can I let it show 

> 中文

 (chinese) instead?

It's annoying especially when using `zh-cn` for traditional chinese, which shows 

> 中文 (简体) (cn)

**Comment by flaviocopes** [comment]
It gets it from an internal reference, you can't change it. But you can override the Twig https://github.com/getgrav/grav-plugin-langswitcher/blob/develop/templates/partials/langswitcher.html.twig#L14 in your theme, copying it to `user/themes/yourtheme/templates/partials` and change it to, for example:

```
...
    {% set lang_name = native_name(key) %}
    {% if lang_name == 'zh' %}
      {% set lang_name = '中文' %}
    {% endif %}
    <li><a href="{{ lang_url ~ uri.params }}" class="external{{ active_class }}">{{  lang_name|capitalize }}</a></li>
...
```

**Comment by kingemir** [comment]
Could you please specify your answer, or provide the entire code for `user/themes/yourtheme/templates/partials/langswitcher.html.twig`, because adding your code or replacing the initial code with your code doesn't provoke the desired result. Thanks. 

Since the internal reference of the plugin contains wrong information, it should be fixed:

- `zh` (chinese) should display '中文'
-  `zh-Hant` (Chinese written using the Traditional Chinese script) should display '繁體中文'
-   `zh-Hans` (Chinese written using the Simplified Chinese script) should display '简体中文'

These language tags follow the [W3C standards](https://www.w3.org/International/articles/language-tags/index.en) (Language subtag plus Script subtag)

**Comment by sunfree-lighting** [comment]
Hi, 

the entire code below works. my language tag is cn and en.  NOT zh-cn.
PS: just change {% set lang_name = native_name(**key**) %} to {% set lang_name = native_name(**language**) %}

The entire code are:
<ul class="langswitcher">
{% for language in langswitcher.languages %}

    {% set show_language = true %}
    {% if language == langswitcher.current %}
        {% set lang_url = page.url %}
        {% set active_class = ' active' %}
    {% else %}
        {% set base_lang_url = base_url_simple ~ grav.language.getLanguageURLPrefix(language) %}
        {% set lang_url = base_lang_url ~ langswitcher.page_route ~ page.urlExtension %}
        {% set untranslated_pages_behavior = grav.config.plugins.langswitcher.untranslated_pages_behavior %}
        {% if untranslated_pages_behavior != 'none' %}
            {% set translated_page = langswitcher.translated_pages[language] %}
            {% if (not translated_page) or (not translated_page.published) %}
                {% if untranslated_pages_behavior == 'redirect' %}
                    {% set lang_url = base_lang_url ~ '/' %}
                {% elseif untranslated_pages_behavior == 'hide' %}
                    {% set show_language = false %}
                {% endif %}
            {% endif %}
        {% endif %}
        {% set active_class = '' %}
    {% endif %}

    {% if show_language %}

         {% set lang_name = native_name(language) %}
           {% if lang_name == 'cn' %}
              {% set lang_name = '中文' %}
           {% endif %}

        <li><a href="{{ lang_url ~ uri.params }}" class="external{{ active_class }}">{{ lang_name|capitalize }}</a></li>



    {% endif %}

{% endfor %}
</ul>
