### ISSUE TITLE
langswitcher with multisite setup ?

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-langswitcher#26]
Do you have an idea how to use langswitcher in a multisite environnment ?

Here's my folder structure
```
- public_html
-- user
--- sites
---- site A
---- site B
```

so for example home page of site A (same issue with all pages)
http://domain.com/sitea

language url 
fr: http://domain.com/sitea
en: http://domain.com/en --> instead of http://domain.com/sitea/en
de: http://domain.com/de --> instead of http://domain.com/sitea/de

 in `system.yaml` :
```
pages:
  redirect_default_route: true
```
Thanks for info

**Comment by rhukster** [comment]
cleaning up old tickets...

multisite might be a problem with multilang.  Really have not run into many people attempting this, you may be the only one!
