### ISSUE TITLE
Inactive language with trailing slash

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-langswitcher#29]
There is problem with the url of the home page for inactive language.
A trailing slash is added even if no extension are set in config.

The problem is visible for both `langswitcher.hreflang.html.twig` and `langswitcher.html.twig`:

For exemple if `English` page is active it render:

```html
<link rel="alternate" href="/en" hreflang="en" />
<link rel="alternate" href="/fr" hreflang="fr/" />
```
and
```html
<ul class="langswitcher">
<li><a class="langswitcher-button" active href="en">English</a></li>
<li><a class="langswitcher-button" href="fr/">Français</a></li>
</ul>
```

The problem is also visible on the `url bar` if redirect trailing slash is set to off in config.

**Comment by jimblue** [comment]
Any update about this?

**Comment by jimblue** [comment]
Nobody around?

**Comment by jimblue** [comment]
Hi @flaviocopes, just wondering if you had time to read this issue and if you consider fix it?

**Comment by jimblue** [comment]
Is this plugin still maintain?

**Comment by rhukster** [comment]
Just busy with other things.  If you can find a fix, propose a Pull Request and i'll take a look.  Cheers.

**Comment by jimblue** [comment]
@rhukster sure I will 😄 !

**Comment by gen035** [comment]
Hey @jimblue I'm having the same issue with a website right now did you find a fix?

**Comment by elemention** [comment]
Has anyone found a solution?

**Comment by gen035** [comment]
@elemention I ended up creating a quick fix in the plugin's template directly:

I added theses lines at line 10 of the `langswitcher.html.twig` file
```
{% if langswitcher.page_route == '/' %}
            {% set lang_url = base_lang_url %}
        {% else %}
            {% set lang_url = base_lang_url ~ langswitcher.page_route ~ page.urlExtension %}
        {% endif %}
```

**Comment by jimblue** [comment]
nope @gen035 didn't find a fix

**Comment by elemention** [comment]
> @elemention I ended up creating a quick fix in the plugin's template directly:
> 
> I added theses lines at line 10 of the `langswitcher.html.twig` file
> 
> ```
> {% if langswitcher.page_route == '/' %}
>             {% set lang_url = base_lang_url %}
>         {% else %}
>             {% set lang_url = base_lang_url ~ langswitcher.page_route ~ page.urlExtension %}
>         {% endif %}
> ```

work like a charm if include_default_lang: true, many thx @gen035 
otherwise if include_default_lang: false, when active now,  for example - IT,  on link of default language EN, we have link of current active lang IT, and link like - localhost/it -  instead - localhost/
maybe i try to found fix later

**Comment by rhukster** [comment]
Pretty sure this has been fixed for a while.
