### ISSUE TITLE
URL's param  disappear when changing language

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-langswitcher#32]
Hi,

Is it possible to keep params in url while changing language.

Thanks

**Comment by yaroslav-khomyak** [comment]
In templates, replace code 

`{{ lang_url ~ uri.params }}`

with

`{{ lang_url ~ (uri.query|length > 1 ? '?' ~ uri.query : uri.params) }}`

**Comment by rhukster** [comment]
old, but this is now included in latest develop branch.
