### ISSUE TITLE
using page's override default_route instead of raw_route

### ISSUE THREAD

**Issue by lpaulger** [getgrav/grav-plugin-langswitcher#35]
I've encountered a scenario that the langswitcher isn't handling as I would expect.

I have my blog under the directory `/knowledge/blog` but I have the default route overridden with `/blog`.
<img width="487" alt="screen shot 2018-03-28 at 12 22 34" src="https://user-images.githubusercontent.com/1000544/38020395-c3a297c2-3282-11e8-9b68-413dbb104f3b.png">

<img width="691" alt="screen shot 2018-03-28 at 12 23 29" src="https://user-images.githubusercontent.com/1000544/38020426-dc95e1d0-3282-11e8-8ad8-59596a2d97b6.png">

grav itself has no issue when routing to the underlying blog pages, or the blog itself. But when I am on a blog page and use the langswitcher because it is using the `rawRoute` it includes the folder structure instead of using the overridden default route

I've been digging around the code a bit and I think in order to make this work, the grav library would need to expose the `default_route` override so that we could make use of it in the langswitcher plugin.

The reason I'm looking to address this is for SEO purposes, we don't want to have the `/knowledge/blog` url showing up at all.

**Comment by lpaulger** [comment]
I realize it might make more sense to override the Canonical route since this is public, and we want to use it in two places. 

would it be fair to do a check for `routeCanonical` before using `rawRoute` ?

**Comment by rhukster** [comment]
Latest version uses full URL that should match any other reference to the page.
