### ISSUE TITLE
How to display a short version of the language name like EN FR ES RU ...

### ISSUE THREAD

**Issue by JOduMonT** [getgrav/grav-plugin-langswitcher#37]
It's more than I'm not a developer and I learn by example but I didn't find anything to show me how to transform this line (I think it is in this line) : `{{ native_name(language)|capitalize }}`

Let's me try to explain what I expect :

I expect to have a **EN / FR** or **en / fr** menu which in html will look like :
`<a href="./en/">EN</a> / <a href="./fr/">FR</a>`

instead of : 
```
            <li>
            <a href="/en/blog.html" class="external">
                English
            </a>
        </li>
            <li>
            <a href="/fr/blog.html" class="external">
                Français
            </a>
        </li>
```

Thanks a lot :)

Jonathan

**Comment by joelluethi** [comment]
Hey Jonathan, I have the same problem/question and I am looking for a solution. Hope someone answers to this!

**Comment by joelluethi** [comment]
Hey @jodumont I found a solution,
Instead of `{{ native_name(language)|capitalize }}` I wrote `{{ key|upper }}`.
This now shows me the short version of the language name.

Hope this helps you too 👍
Joel

**Comment by saidalkharusi** [comment]
For me, `{{ key|upper }}` doesn't output anything. To show the short version I used `{{ language|upper }}`.

**Comment by aeiris** [comment]
Outdated but for newcomers and closing issue #37.

Just use {{ language }} variable inside the for loop that defines this variable in langswitcher.html.twig file:
{% for language in langswitcher.languages %}

{{ language|upper }} gives the uppercase language code (EN,FR)

**Comment by rhukster** [comment]
Short version has been available for a while
