### ISSUE TITLE
Using grav['page']->route() instead of grav['page']->rawRoute()

### ISSUE THREAD

**Issue by jstriedinger** [getgrav/grav-plugin-langswitcher#4]
Hey guys.

This is a very good plugin. Just want suggestion. I noticed you guys use `grav['page']->rawRoute()` to get the route of the page and put it in the href.  The thing is, using rawRoute reject any possible custom routes specified by the user at the page frontmatter.

Example:
I have a page in `pages/evets/myevent` but I want users to be able to enter the page without having to write `/events` part so I do this:
`
routes:
  default: '/myevent'
`
No problem. But the Langswitcher `page_route` variable throws me the `events/myevent` route. Anyway, changing t to `route()`, according to the API docs will: **Gets the route for the page based on the route headers if available, else from the parents route and the current Page's slug**

I believe it will more suitable for customization routes. That or just add another variable in the code, like `custom_route` or something.

**Comment by rhukster** [comment]
Lang switcher is a bit of a special case.  This question keeps getting asked, so i'll refer you to the other closed tickets:

https://github.com/getgrav/grav-plugin-langswitcher/issues/1
https://github.com/getgrav/grav-plugin-langswitcher/issues/2
