### ISSUE TITLE
Plugin doesn't work with include_default_lang: false

### ISSUE THREAD

**Issue by guategeek** [getgrav/grav-plugin-langswitcher#40]
If you have "include_default_lang: false" set (so that your main language doesn't use the language code in the URL (example: site.com/ site.com/fr/ vs site.com/en/ site.com/fr/)) then the language switcher will switch to any non-default language you select, but is unable to switch back to the default one when selected.

**Comment by rhukster** [comment]
Thi sis sorted in latest version with translated urls.
