### ISSUE TITLE
Adding x-default fallback?

### ISSUE THREAD

**Issue by marcocevoli** [getgrav/grav-plugin-langswitcher#41]
Hi,
I might be mistaken, but the plugin currently doesn't output the fallback tag/attribute, such as

`<link rel="alternate" hreflang="x-default" href="https://www.example.com/" />`

According to this article, https://www.contentkingapp.com/academy/hreflang/, the fallback should always be there for SEO reasons.

Any chances that you might add it?

TIA

**Comment by rhukster** [comment]
i'll add it to the list...

**Comment by steopcik** [comment]
> i'll add it to the list...

Hi,
this feature was added or not?

**Comment by plindelauf** [comment]
I needed this as well, so I added it and created a pull request for this: https://github.com/getgrav/grav-plugin-langswitcher/pull/44

**Comment by rhukster** [comment]
I know its very late to the party, but i've now added an x-default entry when the language is default and the include_default_lang option in system.yaml is set to false.  So default lang URLs with no lang prefix will get this x-default entry.
