### ISSUE TITLE
Plugin generates wrong hreflang code

### ISSUE THREAD

**Issue by rlattuad** [getgrav/grav-plugin-langswitcher#43]
I have a blog setup with 2 languages (en, it).
Showing an english page from my blog I get the following:

<link rel="canonical" href="https://blog.eleaflet.eu/en/flu-season-2018-2019-what-is-new" />
<link rel="alternate" hreflang="en" href="/en/flu-season-2018-2019-what-is-new" />
<link rel="alternate" hreflang="it" href="/it/blog/flu-season-2018-2019-what-is-new" />

While the en code is ok, where does the extra /blog/ in the it link come from ? 

Starting from an IT page I get exactly the same problem plus the fact that it does not see EN as the default language and sets the IT page as canonical:

<link rel="canonical" href="https://blog.eleaflet.eu/it/flu-season-2018-2019-what-is-new" />
<link rel="alternate" hreflang="en" href="/en/blog/flu-season-2018-2019-what-is-new" />
<link rel="alternate" hreflang="it" href="/it/flu-season-2018-2019-what-is-new" />

Maybe there is something wrong in the blog configuration ? Where do I set the default language ?

Any help appreciated
Thanks
r

**Comment by rhukster** [comment]
Should be fully sorted with next 3.0 release.
