### ISSUE TITLE
switching works fine on localhost but fails when on the server

### ISSUE THREAD

**Issue by decisaoi** [getgrav/grav-plugin-langswitcher#48]
dear all,

is there any possible configuration on the server-side that could make the switch not functional?

i've installed the plugin on a fresh grav and it works totally fine on the localhost apache + php but as soon as i deploy on an app service on azure with php stack it doesnt work anymore.

**Comment by rhukster** [comment]
definitely an issue related to your azure stack i'm afraid. you should check to make sure grav is fully working and other plugins too.
