### ISSUE TITLE
Not working with G5/hydrogen theme

### ISSUE THREAD

**Issue by gyvermac** [getgrav/grav-plugin-langswitcher#5]
The plugin work perfectly with Antimatter but not with Hydrogen (G5 theme).

As Hydrogen is the base free theme of G5 it could be a good idea to modify either Hydrogen or lanswicher.
I can't figure out to make it work . 
May be it's possible to replace the plugin with an atom or a particle...
Any help will be appreciate.   :-)

**Comment by flaviocopes** [comment]
Gantry is currently not officially working / supported in Grav, you're a bit on the edge, we'll get there soon.

**Comment by mahagr** [comment]
Lets keep this open as we need to address this somehow. :)

**Comment by gyvermac** [comment]
V1.2.1 still not working with Hydrogen....   :-)

**Comment by mahagr** [comment]
Let us finish Gantry 5.3 first. :)

**Comment by rhukster** [comment]
Pretty sure this works fine in G5 now.  Please re-open if you are still having problems.
