### ISSUE TITLE
How to change the Display of the the Languages

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-langswitcher#51]
The functionality of this plugin is flawless. It works as intended. Although, Im kinda new with grav and I wanna achieve something like this, but Ive been trying to configure it but nothing shows up. 

![lang](https://user-images.githubusercontent.com/18525593/87526045-e5d03400-c6bc-11ea-92ad-d9b59c4d3b0d.gif)

If anyone can show me how to put them inside a dropdown and still make it work that'd be awesome! Thanks

**Comment by godfatherjohn** [comment]
The Langswitcher plugin creates an unordered list `<ul>` with an `<li>` entry for each language. You are talking about the layout, which is CSS, in this case. If you want a dropdown, you will need to write up the code for the dropdown yourself or copy from someone who has built such a dropdown.
