### ISSUE TITLE
wrong hreflang genereated when run in subdirectory

### ISSUE THREAD

**Issue by splitbrain** [getgrav/grav-plugin-langswitcher#62]
I'm running my grav site in a subdirectory `site`. I have configured `en` and `de` as languages.

When I am on `http://localhost/site/de/page`, the following `hreflang` entries are generated (using the default partial that comes with the plugin):

```html
<link rel="alternate" hreflang="de" href="http://localhost/site/de/page">
<link rel="alternate" hreflang="en" href="http://localhost/en/page">
```

Clearly the non-active language is generated wrong. Might be related to #43?

**Comment by Maofree** [comment]
Hi
I've found the same error
to fix this issue it is necessary to add "base_url_simple" into langswitcher.hreflang.html.twig
`{% set lang_url = base_url_simple ~ (langobj.getLanguageURLPrefix(key) ~ langswitcher.page_route ~ page.urlExtension ?: '')|rtrim('/') %}`

**Comment by rhukster** [comment]
This should be fixed in latest developer branch.
