### ISSUE TITLE
Lang Switcher URL problem

### ISSUE THREAD

**Issue by benyaminl** [getgrav/grav-plugin-langswitcher#7]
The new update causing problem, the url and data change suddenly to number and only the active language that have the url. see this , even the name change into number. Ah
![1](https://cloud.githubusercontent.com/assets/2817332/15631434/e47bbce6-2594-11e6-9fa4-2f2914e4cbb1.png)
![2](https://cloud.githubusercontent.com/assets/2817332/15631435/fe82d0c0-2594-11e6-9f14-4fe28f2fb178.png)

**Comment by benyaminl** [comment]
ah seems like you change the code, from `{% for key, language in langswitcher.languages %}` to `{% for key in langswitcher.languages %}`butt seems same, the old one use that can produces error anyway, I don't know why, strange.

**Comment by rhukster** [comment]
Hmm... it seems to work fine in my testing.  What dose your `languages: supported:` array look like in your `system.yaml` ?

**Comment by benyaminl** [comment]
Ah this 
`languages:
  supported:
    - en
    - id`

![untitled](https://cloud.githubusercontent.com/assets/2817332/15631601/34af700c-259c-11e6-94e0-604cbd300be7.jpg)

**Comment by rhukster** [comment]
What exactly did you do? Did you update 'just' the langswitcher plugin? maybe try clearing the cache?

**Comment by benyaminl** [comment]
yes also clear cache, it produces (0) and (1), before that it shows 0 and 1, :laughing: I don't know what's going on :confounded:

**Comment by rhukster** [comment]
Your screenshot above shows old langswitcher code. Are you sure you dated it all?  Should of been a change in the .php and .twig

You need both updated files for it to work.

**Comment by benyaminl** [comment]
I updated based on new code you give in your plug ins, it fix the problem, I just ask why it's like that :v: 

I update with the new code and it works

**Comment by rhukster** [comment]
Ok, i'm very confused... is this a legit bug or are things working as expected?  I've changed how the 'native' language is retrieved,  instead of grabbing it right from the array (as before) i have now changed it to pass the key via a twig function to **get** the nativename from the LanguageCodes object.  This allows me to have logic in there that falls back if not found.  This was missing before and was a problem.  

If you are no longer having problems please close the issue.

**Comment by benyaminl** [comment]
Ok, but anyway it should not error right? It fixed because I change the old
code to the new one.
