### ISSUE TITLE
problem after upgrading to 1.2.1

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav-plugin-langswitcher#8]
I have a twig filter named: `{% include 'modular/svg-blog-section-' ~ langswitcher.current ~ '.html.twig' %}` for `svg-blog-section-fr.html.twig`, `svg-blog-section-ja.html.twig` etc...

After upgrade, I have an Runtime 404 error `Template "modular/svg-blog-section-.html.twig" is not defined`

Seems that `langswitcher.current` is not working anymore: what should I do?

**Comment by flaviocopes** [comment]
I'm not seeing anything committed recently that could break this, but use `grav.language.language` instead, it provides the same information.

**Comment by tidiview** [comment]
Thank you for quick answer.
I changed to `grav.language.language` instead, and it went back to normal.
problem occured on modular landing page of site, which is main environnement.

Also, Form has completly disappeared also suddenly from that modular landing page, I am trying to get it back... But I can't get what happened.
